DELETE {
  GRAPH <${graph}> {
  <#list triples as triple>
   <${triple.subject}> <${triple.predicate}> ?o.
  </#list>
  }
}
WHERE  {
    GRAPH <${graph}> {

  <#list triples as triple>
      <${triple.subject}> <${triple.predicate}> ?o.
  </#list>
    }

}
