DELETE {
  GRAPH <${graph}> {
  <#list triples as triple>
   <${triple.subject}> <${triple.predicate}> ?o.
  </#list>
  }
}
  INSERT {
    GRAPH <${graph}> {

  <#list triples as triple>
    <#if triple.language?has_content>

      <${triple.subject}> <${triple.predicate}>  "${triple.object}"@${triple.language}.
      <#elseif triple.datatype?has_content>
      <${triple.subject}> <${triple.predicate}>  "${triple.object}"^^<${triple.datatype}>.
        <#else>
      <${triple.subject}> <${triple.predicate}>  "${triple.object}".
      </#if>

  </#list>

    }
  }
WHERE  {
    GRAPH <${graph}> {

  <#list triples as triple>
      <${triple.subject}> <${triple.predicate}> ?o.
  </#list>
    }

}
