DELETE {
  GRAPH <${graph}> {
  <#list triples as triple>
   <${triple.subject}> <${triple.predicate}> ?o.
  </#list>
  }
}
<#if triple.language?has_content>
  INSERT {
    GRAPH <${graph}> {

  <#list triples as triple>
      <${triple.subject}> <${triple.predicate}>  "${triple.object}"@${triple.language}.
  </#list>

    }
  }
<#elseif triple.datatype?has_content>
  INSERT {
    GRAPH <${graph}> {

  <#list triples as triple>
      <${triple.subject}> <${triple.predicate}>  "${triple.object}"^^<${triple.datatype}>.
  </#list>
    }
  }
<#else>
  INSERT {
    GRAPH <${graph}> {

  <#list triples as triple>
      <${triple.subject}> <${triple.predicate}>  "${triple.object}".
  </#list>
    }
  }
</#if>
WHERE  {
    GRAPH <${graph}> {

  <#list triples as triple>
      <${triple.subject}> <${triple.predicate}> ?o.
  </#list>
    }

}
